<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 11 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary|ClinicalRecord)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth         CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex       CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType CDATA #REQUIRED
>
<!ELEMENT Record ((MetadataEntry|HeartRateVariabilityMetadataList)*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent|WorkoutRoute)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutEvent EMPTY>
<!ATTLIST WorkoutEvent
  type         CDATA #REQUIRED
  date         CDATA #REQUIRED
  duration     CDATA #IMPLIED
  durationUnit CDATA #IMPLIED
>
<!ELEMENT WorkoutRoute ((MetadataEntry|FileReference)*)>
<!ATTLIST WorkoutRoute
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT FileReference EMPTY>
<!ATTLIST FileReference
  path CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleMoveTime            CDATA #IMPLIED
  appleMoveTimeGoal        CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
<!-- Note: Heart Rate Variability records captured by Apple Watch may include an associated list of instantaneous beats-per-minute readings. -->
<!ELEMENT HeartRateVariabilityMetadataList (InstantaneousBeatsPerMinute*)>
<!ELEMENT InstantaneousBeatsPerMinute EMPTY>
<!ATTLIST InstantaneousBeatsPerMinute
  bpm  CDATA #REQUIRED
  time CDATA #REQUIRED
>
<!ELEMENT ClinicalRecord EMPTY>
<!ATTLIST ClinicalRecord
  type              CDATA #REQUIRED
  identifier        CDATA #REQUIRED
  sourceName        CDATA #REQUIRED
  sourceURL         CDATA #REQUIRED
  fhirVersion       CDATA #REQUIRED
  receivedDate      CDATA #REQUIRED
  resourceFilePath  CDATA #REQUIRED
>
<!ELEMENT Audiogram EMPTY>
<!ATTLIST Audiogram
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT SensitivityPoint EMPTY>
<!ATTLIST SensitivityPoint
  frequencyValue   CDATA #REQUIRED
  frequencyUnit    CDATA #REQUIRED
  leftEarValue     CDATA #IMPLIED
  leftEarUnit      CDATA #IMPLIED
  rightEarValue    CDATA #IMPLIED
  rightEarUnit     CDATA #IMPLIED
>
]>
<HealthData locale="ja_JP">
 <ExportDate value="2021-06-06 15:28:16 +0900"/>
 <Me HKCharacteristicTypeIdentifierDateOfBirth="" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexNotSet" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeNotSet" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeNotSet" HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse="なし"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:09:22 +0900" startDate="2021-06-06 14:09:21 +0900" endDate="2021-06-06 14:09:21 +0900" value="102">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:09:27 +0900" startDate="2021-06-06 14:09:26 +0900" endDate="2021-06-06 14:09:26 +0900" value="97">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:09:32 +0900" startDate="2021-06-06 14:09:31 +0900" endDate="2021-06-06 14:09:31 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:09:37 +0900" startDate="2021-06-06 14:09:35 +0900" endDate="2021-06-06 14:09:35 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:09:42 +0900" startDate="2021-06-06 14:09:41 +0900" endDate="2021-06-06 14:09:41 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:09:47 +0900" startDate="2021-06-06 14:09:46 +0900" endDate="2021-06-06 14:09:46 +0900" value="117">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:09:52 +0900" startDate="2021-06-06 14:09:48 +0900" endDate="2021-06-06 14:09:48 +0900" value="117">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:09:57 +0900" startDate="2021-06-06 14:09:52 +0900" endDate="2021-06-06 14:09:52 +0900" value="115">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:10:02 +0900" startDate="2021-06-06 14:10:01 +0900" endDate="2021-06-06 14:10:01 +0900" value="117">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:10:07 +0900" startDate="2021-06-06 14:10:05 +0900" endDate="2021-06-06 14:10:05 +0900" value="116">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:10:12 +0900" startDate="2021-06-06 14:10:07 +0900" endDate="2021-06-06 14:10:07 +0900" value="116">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:10:17 +0900" startDate="2021-06-06 14:10:12 +0900" endDate="2021-06-06 14:10:12 +0900" value="120">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:10:22 +0900" startDate="2021-06-06 14:10:21 +0900" endDate="2021-06-06 14:10:21 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:10:27 +0900" startDate="2021-06-06 14:10:24 +0900" endDate="2021-06-06 14:10:24 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:10:32 +0900" startDate="2021-06-06 14:10:27 +0900" endDate="2021-06-06 14:10:27 +0900" value="120">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:10:37 +0900" startDate="2021-06-06 14:10:36 +0900" endDate="2021-06-06 14:10:36 +0900" value="120">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:10:42 +0900" startDate="2021-06-06 14:10:37 +0900" endDate="2021-06-06 14:10:37 +0900" value="120">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:10:47 +0900" startDate="2021-06-06 14:10:44 +0900" endDate="2021-06-06 14:10:44 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:10:52 +0900" startDate="2021-06-06 14:10:48 +0900" endDate="2021-06-06 14:10:48 +0900" value="119">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:10:57 +0900" startDate="2021-06-06 14:10:52 +0900" endDate="2021-06-06 14:10:52 +0900" value="119">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:11:02 +0900" startDate="2021-06-06 14:10:58 +0900" endDate="2021-06-06 14:10:58 +0900" value="117">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:11:46 +0900" startDate="2021-06-06 14:11:45 +0900" endDate="2021-06-06 14:11:45 +0900" value="65">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:11:51 +0900" startDate="2021-06-06 14:11:50 +0900" endDate="2021-06-06 14:11:50 +0900" value="113">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:11:56 +0900" startDate="2021-06-06 14:11:55 +0900" endDate="2021-06-06 14:11:55 +0900" value="107">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:12:06 +0900" startDate="2021-06-06 14:12:05 +0900" endDate="2021-06-06 14:12:05 +0900" value="69">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:12:41 +0900" startDate="2021-06-06 14:12:40 +0900" endDate="2021-06-06 14:12:40 +0900" value="73">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:12:46 +0900" startDate="2021-06-06 14:12:44 +0900" endDate="2021-06-06 14:12:44 +0900" value="70">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:12:51 +0900" startDate="2021-06-06 14:12:48 +0900" endDate="2021-06-06 14:12:48 +0900" value="69">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:12:56 +0900" startDate="2021-06-06 14:12:51 +0900" endDate="2021-06-06 14:12:51 +0900" value="69">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:13:01 +0900" startDate="2021-06-06 14:13:00 +0900" endDate="2021-06-06 14:13:00 +0900" value="68">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:13:06 +0900" startDate="2021-06-06 14:13:05 +0900" endDate="2021-06-06 14:13:05 +0900" value="67">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:13:21 +0900" startDate="2021-06-06 14:13:17 +0900" endDate="2021-06-06 14:13:17 +0900" value="70">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:13:26 +0900" startDate="2021-06-06 14:13:25 +0900" endDate="2021-06-06 14:13:25 +0900" value="71">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:14:15 +0900" startDate="2021-06-06 14:14:14 +0900" endDate="2021-06-06 14:14:14 +0900" value="81">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:14:21 +0900" startDate="2021-06-06 14:14:15 +0900" endDate="2021-06-06 14:14:15 +0900" value="122">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:14:35 +0900" startDate="2021-06-06 14:14:34 +0900" endDate="2021-06-06 14:14:34 +0900" value="73">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:14:41 +0900" startDate="2021-06-06 14:14:37 +0900" endDate="2021-06-06 14:14:37 +0900" value="71">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:14:45 +0900" startDate="2021-06-06 14:14:40 +0900" endDate="2021-06-06 14:14:40 +0900" value="72">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:14:50 +0900" startDate="2021-06-06 14:14:46 +0900" endDate="2021-06-06 14:14:46 +0900" value="73">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:14:55 +0900" startDate="2021-06-06 14:14:51 +0900" endDate="2021-06-06 14:14:51 +0900" value="73">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:15:06 +0900" startDate="2021-06-06 14:15:03 +0900" endDate="2021-06-06 14:15:03 +0900" value="77">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:15:11 +0900" startDate="2021-06-06 14:15:08 +0900" endDate="2021-06-06 14:15:08 +0900" value="78">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:15:16 +0900" startDate="2021-06-06 14:15:14 +0900" endDate="2021-06-06 14:15:14 +0900" value="77">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:15:20 +0900" startDate="2021-06-06 14:15:19 +0900" endDate="2021-06-06 14:15:19 +0900" value="73">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:15:25 +0900" startDate="2021-06-06 14:15:24 +0900" endDate="2021-06-06 14:15:24 +0900" value="72">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:15:30 +0900" startDate="2021-06-06 14:15:28 +0900" endDate="2021-06-06 14:15:28 +0900" value="71">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:15:35 +0900" startDate="2021-06-06 14:15:33 +0900" endDate="2021-06-06 14:15:33 +0900" value="71">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:15:40 +0900" startDate="2021-06-06 14:15:35 +0900" endDate="2021-06-06 14:15:35 +0900" value="71">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:15:46 +0900" startDate="2021-06-06 14:15:41 +0900" endDate="2021-06-06 14:15:41 +0900" value="71">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:15:50 +0900" startDate="2021-06-06 14:15:49 +0900" endDate="2021-06-06 14:15:49 +0900" value="71">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:15:55 +0900" startDate="2021-06-06 14:15:51 +0900" endDate="2021-06-06 14:15:51 +0900" value="71">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:16:49 +0900" startDate="2021-06-06 14:16:48 +0900" endDate="2021-06-06 14:16:48 +0900" value="77">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:16:54 +0900" startDate="2021-06-06 14:16:53 +0900" endDate="2021-06-06 14:16:53 +0900" value="74">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x282303bb0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-06-06 14:16:59 +0900" startDate="2021-06-06 14:16:54 +0900" endDate="2021-06-06 14:16:54 +0900" value="75">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>