<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 11 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary|ClinicalRecord)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth         CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex       CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType CDATA #REQUIRED
>
<!ELEMENT Record ((MetadataEntry|HeartRateVariabilityMetadataList)*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent|WorkoutRoute)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutEvent EMPTY>
<!ATTLIST WorkoutEvent
  type         CDATA #REQUIRED
  date         CDATA #REQUIRED
  duration     CDATA #IMPLIED
  durationUnit CDATA #IMPLIED
>
<!ELEMENT WorkoutRoute ((MetadataEntry|FileReference)*)>
<!ATTLIST WorkoutRoute
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT FileReference EMPTY>
<!ATTLIST FileReference
  path CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleMoveTime            CDATA #IMPLIED
  appleMoveTimeGoal        CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
<!-- Note: Heart Rate Variability records captured by Apple Watch may include an associated list of instantaneous beats-per-minute readings. -->
<!ELEMENT HeartRateVariabilityMetadataList (InstantaneousBeatsPerMinute*)>
<!ELEMENT InstantaneousBeatsPerMinute EMPTY>
<!ATTLIST InstantaneousBeatsPerMinute
  bpm  CDATA #REQUIRED
  time CDATA #REQUIRED
>
<!ELEMENT ClinicalRecord EMPTY>
<!ATTLIST ClinicalRecord
  type              CDATA #REQUIRED
  identifier        CDATA #REQUIRED
  sourceName        CDATA #REQUIRED
  sourceURL         CDATA #REQUIRED
  fhirVersion       CDATA #REQUIRED
  receivedDate      CDATA #REQUIRED
  resourceFilePath  CDATA #REQUIRED
>
<!ELEMENT Audiogram EMPTY>
<!ATTLIST Audiogram
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT SensitivityPoint EMPTY>
<!ATTLIST SensitivityPoint
  frequencyValue   CDATA #REQUIRED
  frequencyUnit    CDATA #REQUIRED
  leftEarValue     CDATA #IMPLIED
  leftEarUnit      CDATA #IMPLIED
  rightEarValue    CDATA #IMPLIED
  rightEarUnit     CDATA #IMPLIED
>
]>
<HealthData locale="ja_JP">
 <ExportDate value="2021-12-28 19:46:05 +0900"/>
 <Me HKCharacteristicTypeIdentifierDateOfBirth="" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexNotSet" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeNotSet" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeNotSet" HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse="なし"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:49:45 +0900" startDate="2021-12-28 14:49:44 +0900" endDate="2021-12-28 14:49:44 +0900" value="97">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:50:05 +0900" startDate="2021-12-28 14:50:02 +0900" endDate="2021-12-28 14:50:02 +0900" value="128">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:50:10 +0900" startDate="2021-12-28 14:50:09 +0900" endDate="2021-12-28 14:50:09 +0900" value="128">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:50:15 +0900" startDate="2021-12-28 14:50:10 +0900" endDate="2021-12-28 14:50:10 +0900" value="128">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:50:20 +0900" startDate="2021-12-28 14:50:15 +0900" endDate="2021-12-28 14:50:15 +0900" value="128">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:50:25 +0900" startDate="2021-12-28 14:50:20 +0900" endDate="2021-12-28 14:50:20 +0900" value="128">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:50:30 +0900" startDate="2021-12-28 14:50:29 +0900" endDate="2021-12-28 14:50:29 +0900" value="42">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:50:35 +0900" startDate="2021-12-28 14:50:34 +0900" endDate="2021-12-28 14:50:34 +0900" value="42">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:52:09 +0900" startDate="2021-12-28 14:52:08 +0900" endDate="2021-12-28 14:52:08 +0900" value="54">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:52:14 +0900" startDate="2021-12-28 14:52:13 +0900" endDate="2021-12-28 14:52:13 +0900" value="47">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:52:19 +0900" startDate="2021-12-28 14:52:18 +0900" endDate="2021-12-28 14:52:18 +0900" value="46">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:52:24 +0900" startDate="2021-12-28 14:52:19 +0900" endDate="2021-12-28 14:52:19 +0900" value="45">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:52:29 +0900" startDate="2021-12-28 14:52:27 +0900" endDate="2021-12-28 14:52:27 +0900" value="45">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:52:34 +0900" startDate="2021-12-28 14:52:31 +0900" endDate="2021-12-28 14:52:31 +0900" value="46">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:52:39 +0900" startDate="2021-12-28 14:52:38 +0900" endDate="2021-12-28 14:52:38 +0900" value="46">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:52:44 +0900" startDate="2021-12-28 14:52:40 +0900" endDate="2021-12-28 14:52:40 +0900" value="46">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:52:49 +0900" startDate="2021-12-28 14:52:46 +0900" endDate="2021-12-28 14:52:46 +0900" value="45">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:52:54 +0900" startDate="2021-12-28 14:52:52 +0900" endDate="2021-12-28 14:52:52 +0900" value="45">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:52:59 +0900" startDate="2021-12-28 14:52:58 +0900" endDate="2021-12-28 14:52:58 +0900" value="45">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:53:04 +0900" startDate="2021-12-28 14:53:03 +0900" endDate="2021-12-28 14:53:03 +0900" value="45">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:53:09 +0900" startDate="2021-12-28 14:53:07 +0900" endDate="2021-12-28 14:53:07 +0900" value="45">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:53:14 +0900" startDate="2021-12-28 14:53:11 +0900" endDate="2021-12-28 14:53:11 +0900" value="45">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:53:19 +0900" startDate="2021-12-28 14:53:15 +0900" endDate="2021-12-28 14:53:15 +0900" value="46">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:53:24 +0900" startDate="2021-12-28 14:53:23 +0900" endDate="2021-12-28 14:53:23 +0900" value="46">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:53:29 +0900" startDate="2021-12-28 14:53:24 +0900" endDate="2021-12-28 14:53:24 +0900" value="45">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:53:34 +0900" startDate="2021-12-28 14:53:31 +0900" endDate="2021-12-28 14:53:31 +0900" value="45">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:53:39 +0900" startDate="2021-12-28 14:53:35 +0900" endDate="2021-12-28 14:53:35 +0900" value="45">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:53:44 +0900" startDate="2021-12-28 14:53:43 +0900" endDate="2021-12-28 14:53:43 +0900" value="45">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:53:49 +0900" startDate="2021-12-28 14:53:46 +0900" endDate="2021-12-28 14:53:46 +0900" value="45">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:54:53 +0900" startDate="2021-12-28 14:54:52 +0900" endDate="2021-12-28 14:54:52 +0900" value="67">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:54:58 +0900" startDate="2021-12-28 14:54:57 +0900" endDate="2021-12-28 14:54:57 +0900" value="52">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:55:03 +0900" startDate="2021-12-28 14:55:02 +0900" endDate="2021-12-28 14:55:02 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:55:08 +0900" startDate="2021-12-28 14:55:06 +0900" endDate="2021-12-28 14:55:06 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:55:13 +0900" startDate="2021-12-28 14:55:12 +0900" endDate="2021-12-28 14:55:12 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:55:18 +0900" startDate="2021-12-28 14:55:15 +0900" endDate="2021-12-28 14:55:15 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:55:23 +0900" startDate="2021-12-28 14:55:20 +0900" endDate="2021-12-28 14:55:20 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:55:28 +0900" startDate="2021-12-28 14:55:24 +0900" endDate="2021-12-28 14:55:24 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:55:33 +0900" startDate="2021-12-28 14:55:30 +0900" endDate="2021-12-28 14:55:30 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:55:38 +0900" startDate="2021-12-28 14:55:35 +0900" endDate="2021-12-28 14:55:35 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:55:43 +0900" startDate="2021-12-28 14:55:42 +0900" endDate="2021-12-28 14:55:42 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:55:48 +0900" startDate="2021-12-28 14:55:43 +0900" endDate="2021-12-28 14:55:43 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:55:53 +0900" startDate="2021-12-28 14:55:48 +0900" endDate="2021-12-28 14:55:48 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:55:58 +0900" startDate="2021-12-28 14:55:56 +0900" endDate="2021-12-28 14:55:56 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:56:03 +0900" startDate="2021-12-28 14:56:00 +0900" endDate="2021-12-28 14:56:00 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:56:08 +0900" startDate="2021-12-28 14:56:03 +0900" endDate="2021-12-28 14:56:03 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:56:13 +0900" startDate="2021-12-28 14:56:12 +0900" endDate="2021-12-28 14:56:12 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:56:18 +0900" startDate="2021-12-28 14:56:15 +0900" endDate="2021-12-28 14:56:15 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:56:23 +0900" startDate="2021-12-28 14:56:18 +0900" endDate="2021-12-28 14:56:18 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:56:28 +0900" startDate="2021-12-28 14:56:26 +0900" endDate="2021-12-28 14:56:26 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:56:33 +0900" startDate="2021-12-28 14:56:30 +0900" endDate="2021-12-28 14:56:30 +0900" value="50">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:57:21 +0900" startDate="2021-12-28 14:57:20 +0900" endDate="2021-12-28 14:57:20 +0900" value="58">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:57:26 +0900" startDate="2021-12-28 14:57:25 +0900" endDate="2021-12-28 14:57:25 +0900" value="56">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:57:31 +0900" startDate="2021-12-28 14:57:30 +0900" endDate="2021-12-28 14:57:30 +0900" value="55">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x281827de0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-12-28 14:57:36 +0900" startDate="2021-12-28 14:57:34 +0900" endDate="2021-12-28 14:57:34 +0900" value="55">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>