<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 11 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary|ClinicalRecord)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth         CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex       CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType CDATA #REQUIRED
>
<!ELEMENT Record ((MetadataEntry|HeartRateVariabilityMetadataList)*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent|WorkoutRoute)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutEvent EMPTY>
<!ATTLIST WorkoutEvent
  type         CDATA #REQUIRED
  date         CDATA #REQUIRED
  duration     CDATA #IMPLIED
  durationUnit CDATA #IMPLIED
>
<!ELEMENT WorkoutRoute ((MetadataEntry|FileReference)*)>
<!ATTLIST WorkoutRoute
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT FileReference EMPTY>
<!ATTLIST FileReference
  path CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleMoveTime            CDATA #IMPLIED
  appleMoveTimeGoal        CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
<!-- Note: Heart Rate Variability records captured by Apple Watch may include an associated list of instantaneous beats-per-minute readings. -->
<!ELEMENT HeartRateVariabilityMetadataList (InstantaneousBeatsPerMinute*)>
<!ELEMENT InstantaneousBeatsPerMinute EMPTY>
<!ATTLIST InstantaneousBeatsPerMinute
  bpm  CDATA #REQUIRED
  time CDATA #REQUIRED
>
<!ELEMENT ClinicalRecord EMPTY>
<!ATTLIST ClinicalRecord
  type              CDATA #REQUIRED
  identifier        CDATA #REQUIRED
  sourceName        CDATA #REQUIRED
  sourceURL         CDATA #REQUIRED
  fhirVersion       CDATA #REQUIRED
  receivedDate      CDATA #REQUIRED
  resourceFilePath  CDATA #REQUIRED
>
<!ELEMENT Audiogram EMPTY>
<!ATTLIST Audiogram
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT SensitivityPoint EMPTY>
<!ATTLIST SensitivityPoint
  frequencyValue   CDATA #REQUIRED
  frequencyUnit    CDATA #REQUIRED
  leftEarValue     CDATA #IMPLIED
  leftEarUnit      CDATA #IMPLIED
  rightEarValue    CDATA #IMPLIED
  rightEarUnit     CDATA #IMPLIED
>
]>
<HealthData locale="ja_JP">
 <ExportDate value="2021-05-28 21:17:47 +0900"/>
 <Me HKCharacteristicTypeIdentifierDateOfBirth="" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexNotSet" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeNotSet" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeNotSet" HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse="なし"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:51:19 +0900" startDate="2021-05-28 16:51:17 +0900" endDate="2021-05-28 16:51:17 +0900" value="62">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:51:23 +0900" startDate="2021-05-28 16:51:21 +0900" endDate="2021-05-28 16:51:21 +0900" value="60">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:51:28 +0900" startDate="2021-05-28 16:51:25 +0900" endDate="2021-05-28 16:51:25 +0900" value="60">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:51:33 +0900" startDate="2021-05-28 16:51:32 +0900" endDate="2021-05-28 16:51:32 +0900" value="60">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:51:38 +0900" startDate="2021-05-28 16:51:37 +0900" endDate="2021-05-28 16:51:37 +0900" value="60">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:51:43 +0900" startDate="2021-05-28 16:51:42 +0900" endDate="2021-05-28 16:51:42 +0900" value="60">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:51:48 +0900" startDate="2021-05-28 16:51:47 +0900" endDate="2021-05-28 16:51:47 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:51:53 +0900" startDate="2021-05-28 16:51:48 +0900" endDate="2021-05-28 16:51:48 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:51:59 +0900" startDate="2021-05-28 16:51:55 +0900" endDate="2021-05-28 16:51:55 +0900" value="117">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:52:04 +0900" startDate="2021-05-28 16:51:59 +0900" endDate="2021-05-28 16:51:59 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:52:08 +0900" startDate="2021-05-28 16:52:07 +0900" endDate="2021-05-28 16:52:07 +0900" value="117">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:52:14 +0900" startDate="2021-05-28 16:52:09 +0900" endDate="2021-05-28 16:52:09 +0900" value="117">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:52:19 +0900" startDate="2021-05-28 16:52:17 +0900" endDate="2021-05-28 16:52:17 +0900" value="119">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:52:24 +0900" startDate="2021-05-28 16:52:22 +0900" endDate="2021-05-28 16:52:22 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:52:28 +0900" startDate="2021-05-28 16:52:24 +0900" endDate="2021-05-28 16:52:24 +0900" value="119">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:52:34 +0900" startDate="2021-05-28 16:52:31 +0900" endDate="2021-05-28 16:52:31 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:52:39 +0900" startDate="2021-05-28 16:52:33 +0900" endDate="2021-05-28 16:52:33 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:52:44 +0900" startDate="2021-05-28 16:52:41 +0900" endDate="2021-05-28 16:52:41 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:52:49 +0900" startDate="2021-05-28 16:52:47 +0900" endDate="2021-05-28 16:52:47 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:52:53 +0900" startDate="2021-05-28 16:52:50 +0900" endDate="2021-05-28 16:52:50 +0900" value="117">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:52:59 +0900" startDate="2021-05-28 16:52:53 +0900" endDate="2021-05-28 16:52:53 +0900" value="118">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:53:42 +0900" startDate="2021-05-28 16:53:40 +0900" endDate="2021-05-28 16:53:40 +0900" value="66">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:53:47 +0900" startDate="2021-05-28 16:53:45 +0900" endDate="2021-05-28 16:53:45 +0900" value="67">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:53:52 +0900" startDate="2021-05-28 16:53:51 +0900" endDate="2021-05-28 16:53:51 +0900" value="66">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:53:57 +0900" startDate="2021-05-28 16:53:56 +0900" endDate="2021-05-28 16:53:56 +0900" value="65">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:54:02 +0900" startDate="2021-05-28 16:54:01 +0900" endDate="2021-05-28 16:54:01 +0900" value="65">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:54:07 +0900" startDate="2021-05-28 16:54:02 +0900" endDate="2021-05-28 16:54:02 +0900" value="66">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:54:12 +0900" startDate="2021-05-28 16:54:07 +0900" endDate="2021-05-28 16:54:07 +0900" value="66">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:54:17 +0900" startDate="2021-05-28 16:54:16 +0900" endDate="2021-05-28 16:54:16 +0900" value="66">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:54:22 +0900" startDate="2021-05-28 16:54:21 +0900" endDate="2021-05-28 16:54:21 +0900" value="65">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:54:27 +0900" startDate="2021-05-28 16:54:26 +0900" endDate="2021-05-28 16:54:26 +0900" value="65">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:54:32 +0900" startDate="2021-05-28 16:54:31 +0900" endDate="2021-05-28 16:54:31 +0900" value="65">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:54:37 +0900" startDate="2021-05-28 16:54:32 +0900" endDate="2021-05-28 16:54:32 +0900" value="65">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:54:42 +0900" startDate="2021-05-28 16:54:41 +0900" endDate="2021-05-28 16:54:41 +0900" value="65">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:54:47 +0900" startDate="2021-05-28 16:54:43 +0900" endDate="2021-05-28 16:54:43 +0900" value="65">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:54:52 +0900" startDate="2021-05-28 16:54:51 +0900" endDate="2021-05-28 16:54:51 +0900" value="65">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:54:57 +0900" startDate="2021-05-28 16:54:53 +0900" endDate="2021-05-28 16:54:53 +0900" value="64">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:55:02 +0900" startDate="2021-05-28 16:54:57 +0900" endDate="2021-05-28 16:54:57 +0900" value="65">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:55:07 +0900" startDate="2021-05-28 16:55:06 +0900" endDate="2021-05-28 16:55:06 +0900" value="66">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:55:12 +0900" startDate="2021-05-28 16:55:11 +0900" endDate="2021-05-28 16:55:11 +0900" value="65">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:55:17 +0900" startDate="2021-05-28 16:55:14 +0900" endDate="2021-05-28 16:55:14 +0900" value="65">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:55:22 +0900" startDate="2021-05-28 16:55:21 +0900" endDate="2021-05-28 16:55:21 +0900" value="65">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:55:23 +0900" startDate="2021-05-28 16:50:41 +0900" endDate="2021-05-28 16:50:41 +0900" value="82">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:56:07 +0900" startDate="2021-05-28 16:56:05 +0900" endDate="2021-05-28 16:56:05 +0900" value="68">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:56:12 +0900" startDate="2021-05-28 16:56:08 +0900" endDate="2021-05-28 16:56:08 +0900" value="68">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:56:17 +0900" startDate="2021-05-28 16:56:16 +0900" endDate="2021-05-28 16:56:16 +0900" value="69">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:56:22 +0900" startDate="2021-05-28 16:56:19 +0900" endDate="2021-05-28 16:56:19 +0900" value="69">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:56:27 +0900" startDate="2021-05-28 16:56:26 +0900" endDate="2021-05-28 16:56:26 +0900" value="70">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:56:32 +0900" startDate="2021-05-28 16:56:29 +0900" endDate="2021-05-28 16:56:29 +0900" value="70">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:56:37 +0900" startDate="2021-05-28 16:56:33 +0900" endDate="2021-05-28 16:56:33 +0900" value="70">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:56:42 +0900" startDate="2021-05-28 16:56:38 +0900" endDate="2021-05-28 16:56:38 +0900" value="71">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:56:47 +0900" startDate="2021-05-28 16:56:44 +0900" endDate="2021-05-28 16:56:44 +0900" value="70">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:56:52 +0900" startDate="2021-05-28 16:56:51 +0900" endDate="2021-05-28 16:56:51 +0900" value="70">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="藤井敦寛のApple Watch" sourceVersion="7.5" device="&lt;&lt;HKDevice: 0x283c04d20&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch5,4, software:7.5&gt;" unit="count/min" creationDate="2021-05-28 16:56:57 +0900" startDate="2021-05-28 16:56:54 +0900" endDate="2021-05-28 16:56:54 +0900" value="69">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>